export const ENTITY_TYPE = {
  REVIEW: "Review",
  REVIEW_REPORT: "ReviewReport",
  REVIEW_IMAGE: "ReviewImage",
  SHIP: "Ship",
  RESOURCE: "Resource",
  STATUS: "Status",
  ADDRESS: "Address",
  PERMISSION: "Permission",
  ROLE: "Role",
  ROLE_PERMISSION: "RolePermission",
  USER_ROLE_DETAIL: "UserRoleDetail",
  USER: "User",
  PAYMENT: "Payment",
  PAYMENT_DESTINATION: "PaymentDestination",
  PAYMENT_METHOD: "PaymentMethod",
  CATEGORY: "Category",
  COLOR: "Color",
  MATERIAL: "Material",
  PRODUCT: "Product",
  PRODUCT_IMAGE: "ProductImage",
  PRODUCT_VARIANT: "ProductVariant",
  SIZE: "Size",
  SUPPLIER: "Supplier",
  DISCOUNT: "Discount",
  CART: "Cart",
  CART_ITEM: "CartItem",
  ORDER: "Order",
  ORDER_ITEM: "OrderItem",
  PRODUCT_RETURN: "ProductReturn",
  PURCHASE_ORDER: "PurchaseOrder",
  PURCHASE_ORDER_ITEM: "PurchaseOrderItem",
  PRODUCT_GROUP: "ProductGroup",
} as const;

export type EntityType = (typeof ENTITY_TYPE)[keyof typeof ENTITY_TYPE];
